FROM node:20.13.0-alpine3.19 AS builder

WORKDIR /app

COPY tsconfig.json .
COPY package*.json .
RUN --mount=type=cache,target="/root/.npm" npm ci --no-audit --no-fund

COPY src/ src
RUN npm run build


FROM node:20.13.0-alpine3.19

ARG node_env=production
ENV NODE_ENV=$node_env

RUN --mount=type=cache,target="/var/cache/apk" apk update && apk add \
    bash \
    bind-tools \
    ca-certificates \
    coreutils \
    curl \
    expect \
    iputils-ping \
    jq \
    mtr \
    traceroute \
    util-linux-misc

WORKDIR /app

COPY bin/entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

COPY config/ config

COPY package*.json .
RUN --mount=type=cache,target="/root/.npm" npm ci --no-audit --no-fund

COPY --from=builder /app/dist /app/dist
